### ISSUE TITLE
Feature Request: Banner for un-authenticated users

### ISSUE THREAD

**Issue by ForrestHerman** [akiko-pusu/redmine_banner#126]
I was wondering if it would be possible to configure the banner to only appear for users who are not currently logged in or belong to a specific user group?

**Comment by akiko-pusu** [comment]
Hi, @ForrestHerman 
Thanks for your request.

I've implemented this feature and merged it into the dev branch.
Soon I'm going to release a new version including this.

**Comment by akiko-pusu** [comment]
Released v0.3.1. Please try if you have time!
