### ISSUE TITLE
HTML problems on redmine_banner 0.3.1

### ISSUE THREAD

**Issue by ryouma-nagare** [akiko-pusu/redmine_banner#134]
## Summary

![image](https://user-images.githubusercontent.com/12542118/80461712-a6713180-8970-11ea-8ef8-9f69716ca0e0.png)

1. Can't Display "enable" label
1. edit link is wrong

## Environment

- Redmine 4.0.7.stable.19713
- Installed plugins
```
  redmine_absolute_dates         0.0.4
  redmine_banner                 0.3.1
  redmine_code_review            1.0.0
  redmine_issue_templates        1.0.1
  redmine_jstoolbar_ext          0.2.1
  redmine_jstoolbar_ext_buttons  0.2.1
  redmine_persist_wfmt           2.0.1
  redmine_searchable_selectbox   0.1.0
  redmine_vividtone_my_page_blocks 2017/07/05
  redmine_wiki_extensions        0.9.0
  redmine_wiki_index_tree_view   0.0.1
  redmine_wiki_lists             0.0.9
  redmine_wiki_page_tree         0.0.1
  redmine_work_time              0.4.0
  redmine_xls_export             0.2.1.t11
  view_customize                 2.6.0
```
- Ruby 2.5.7-p206
- CentOS7.7
- PostgreSQL 11.7
- Rails 5.2.4.2

## Expected Results

1. Display "enable" label
redmine_banner/app/views/banner/show.html.erb

AsIs
```
<div id="banner_setting'>
```

ToBe
```
<div id="banner_setting">
```

2. edit link 

AsIs
```
<a class="icon banner-icon-edit" title="編集" href="/redmine/projects/project-X/settings/banner">編集</a>
```

ToBe
```
<a class="icon banner-icon-edit" title="編集" href="/redmine/projects/project-X/banner">編集</a>
```
- no "settings" required

There was no problem in operation with version 0.3.0

**Comment by akiko-pusu** [comment]
Thanks for reporting this terrible bug!!!!!

**Comment by akiko-pusu** [comment]
Sorry, I've just fixed this problem and released bugfix version.
