### ISSUE TITLE
admin-page: translation failure

### ISSUE THREAD

**Issue by teatower** [akiko-pusu/redmine_banner#142]
Hello everybody,

THANK YOU for this very well designed plugin.
I am still new at github, so I do not know if this is the right place to report.

The plugin-administration page displays almost all item descriptions in the correct language (in my case: german) but on element is displayed in english. It's the description of the banner admin group
"Specify a group that can manage the global banner without admin rights."

May I be of some help with a translation for this?
"Gruppe, die globale Banner auch ohne Admin-Rechte verwalten darf."

Also "Display for"
would be "Banner anzeigen allen"
-->authenticated users --> "eingeloggten Benutzern"
-->anonymous users --> "unbekannten Benutzern"
-->All --> "Allen"

I do hope, this could be of some help an further improve your toll.

Thanks,
teatower

**Comment by akiko-pusu** [comment]
Hi, @teatower 
Thanks for your reporting this issue!

In Redmine (and Rails application), we have translation files for each language.
In this case, German translation does not exist and default language English is applied.

See English translation file:
https://github.com/akiko-pusu/redmine_banner/blob/50df2c5ea2dbbd36d75ea3c3e4602458ac809714/config/locales/en.yml#L30

And German translation file us here.
- https://github.com/akiko-pusu/redmine_banner/blob/master/config/locales/de.yml

Now localization works are supported by the volunteers.
If you don't mind, could you please give me these missing translations for German?
(Both welcomed: Sending a pull request or writing down translated messages on this issue)  

https://github.com/akiko-pusu/redmine_banner/blob/50df2c5ea2dbbd36d75ea3c3e4602458ac809714/config/locales/en.yml#L29-L34

Of course, I can add the translation by myself.
In any cases, I'm going to add your name as a contributor!

**Comment by teatower** [comment]
Hi,

sorry, I tried hard, but as I am not a real programmer, I do not have a deeper insight knowledge about github and could not really find out, how to pull a request.
Please accept it the way that I copy the _already corrected_ language file below in total.
Thank you.

It is a pleasure to give at least a little back in exchange to use this great plugin.

Stay safe and healthy,
teatower

# German strings go here for Rails i18n
de:
  banner: "Banner"
  setting_banner_display_part: "Anzeigeposition"
  label_header_only: "Nur Kopfzeile"
  label_footer_only: "Nur Fußzeile"
  label_both: "Kopf und Fußzeile"
  label_banner_message: "Banner Nachricht"
  label_message_type: "Nachrichtenart"
  label_start_datetime: "Startzeitpunkt"
  label_end_datetime: "Endzeitpunkt"
  label_use_timer: "Timer benutzen"
  error_banner_date_range: "Der Startzeitpunkt muss vor dem Endzeitpunkt liegen."
  redmine_banner_title: "Springe zu den Banner Einstellungen."
  button_off: "Deaktivieren"
  banner_off: "Deaktiviert das Banner."
  permission_manage_banner: "Banner verwalten"
  project_module_banner: "Banner"
  page_overview_only: "Nur auf der Übersichtsseite"
  page_all: "Auf allen Seiten"
  page_overview_and_issues: "Auf der Übersichtsseite und Ticketübersicht"
  page_new_issue_only: "Nur auf der Seite für neue Tickets"  
  label_display_authenticated_user_only: "Banner nur bei authentifizierten Benutzern anzeigen."
  label_check_if_banner_show_only_login_page: "Option: Banner nur auf der Login Seite anzeigen."
  setting_banner_related_link: "Zugehöriger Link"
  setting_banner_related_link_description: "Wenn ein zugehöriger Link definiert ist, wird er an die Informationen angehängt."
  more_info: "[Weitere Informationen]"
  label_more_info: "Link zu weiteren Informationen." 
  banner_admin_group: "Gruppe für Banneradministration" 
  description_for_banner_admin_group: "Gruppe, die globale Banner auch ohne Admin-Rechte verwalten darf." 
  setting_banner_display_for: "Banner anzeigen für" 
  label_anonymous_only: "Anonyme Benutzer" 
  label_authenticated_only: "Eingeloggte Benutzer" 
  label_display_all: "Alle"

**Comment by akiko-pusu** [comment]
Hi, thanks for your reply! I really appreciated it!
Wishing you to stay safe & healthy 😄

**Comment by akiko-pusu** [comment]
I've just released v0.3.4, including your translation messages.
It is very valuable information for me to know that this plugin is still used in various environments.
