### ISSUE TITLE
Internal error

### ISSUE THREAD

**Issue by huangxh16888** [akiko-pusu/redmine_banner#38]
I've installed the plugin and restarted Redmine , but then when I try to navigate to redmine  the following error apears in page:
Internal error

An error occurred on the page you were trying to access.
If you continue to experience problems please contact your Redmine administrator for assistance.

If you are the Redmine administrator, check your log files for details about the error.

and the log:

ActionView::Template::Error (Missing partial banner/project_body_bottom with {:locale=>[:zh, :en], :formats=>[:html], :handlers=>[:erb, :builder, :rsb]}. Searched in:
- "/opt/bitnami/apps/redmine/htdocs/app/views"
  ):
  56:         <%= view_layouts_base_sidebar_hook_response %>
  57:     </div>
  58: 
  59:     <div id="content">
  60:         <%= render_flash_messages %>
  61:         <%= yield %>
  62:         <%= call_hook :view_layouts_base_content %>
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in`each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in`tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:158:in`call_hook'
  app/views/layouts/base.html.erb:59:in `_app_views_layouts_base_html_erb___3927069031350559510_52561340'
  app/controllers/application_controller.rb:397:in`block (2 levels) in render_error'
  app/controllers/application_controller.rb:395:in `render_error'
  app/controllers/application_controller.rb:383:in`render_404'
  app/controllers/application_controller.rb:407:in `missing_template'

ruby script/about:

 Environment:
Redmine version 2.3.1.stable
Ruby version 1.9.3 (x86_64 -linux)
Rails version 3.2.13
Environment production
Database adapter MySQL2
Redmine plugins:
redmine_banner 0.0.9

**Comment by ElskerDane** [comment]
This helped me!  Thank you!

**Comment by akiko-pusu** [comment]
@ElskerDane I am glad to hear that!
