### ISSUE TITLE
Per project banner configuration not visible

### ISSUE THREAD

**Issue by joserwan** [akiko-pusu/redmine_banner#40]
Hi,

At first, thank you for this useful plugin !

Since an upgrade to Redmine 2.2.0.devel.4243, the configuration tab of banner in my projects is not visible anymore. (global banner works fine, and I double checked banner module was activated in my project)

I have reinstalled the plugin and ran the migrations, and it didn't fix. (I tried master branch and tag 0.0.9.)

Is my upgrade process wrong ?

Thank you.

**Comment by mettlerr** [comment]
Hello akiko-pusu

I have the same problem, and I believe it is because of the Redmine Checklists plugin, which is also from RedmineCRM, like the "RedmineCRM Contacts" plugin. Any updated on a patch for this problem? I am using the latest version of the Banner plugin 0.1.1.

**Comment by dr-itz** [comment]
see https://github.com/dr-itz/RedminePlannerPlugin/issues/22
redmine_banner is correct. Any plugin that messes with the tabs using a tabs.select() is wrong and needs fixing.

**Comment by akiko-pusu** [comment]
@dr-itz Thank you so much your comment above!
And sorry for my reply is toooo late..... I’m going to close this issue.
