### ISSUE TITLE
You are duplicating unique CSS IDs in your code making impossible to style your banners correctly

### ISSUE THREAD

**Issue by spydmobile** [akiko-pusu/redmine_banner#45]
Hi, Love your module and use it on all my redmine sites. It is however difficult to work with when making your own themes or custom CSS. You have given us an option to put banners at the top and bottom of the page but you gave them both the same ID (CSS bad practice) Your plugin would work better with themes and other plugin (like custom css plugin) if you allow us to style each banner (top and bottom) separately. As it stand now, to move the banner out of the way for breadcrumbs with a margin I must also move the bottom one down the page. If  you Change the banner div ids to banner_top and banner_bottom, this could easily be 10x more stylable.

**Comment by akiko-pusu** [comment]
Fixed: 8b02443
This update is included next release.
