### ISSUE TITLE
Compatibility with Easy Redmine?

### ISSUE THREAD

**Issue by fcappz** [akiko-pusu/redmine_banner#49]
We're considering getting EasyRedmine for functionality not available via other Redmine plugins. Has this plugin been tested or used with EasyRedmine?  Thanks.

**Comment by akiko-pusu** [comment]
@fcappz , thank you for your interest in my small plugin and question.
I'm sorry for my delayed reply and sorry I have not use EasyRedmine yet.

But, personally, I think this plugin is enabled to use on Easy Redmine.
