### ISSUE TITLE
Spanish strings go here for Rails i18n

### ISSUE THREAD

**Issue by Picazamora** [akiko-pusu/redmine_banner#52]
This is my contribution ;)

# Spanish strings go here for Rails i18n
es:
  banner: "Baner"
  setting_banner_display_part: "Posición en la pantalla"
  label_header_only: "Solo en la cabecera"
  label_footer_only: "Solo en el pie"
  label_both: "Cabecera y pie"
  label_banner_message: "Mensaje del baner"
  label_message_type: "Tipo de mensaje"
  label_start_datetime: "Fecha y hora de inicio"
  label_end_datetime: "Fecha y hora de fin"
  label_use_timer: "Temporizador"
  error_banner_date_range: "La fecha de inicio debe ser anterior a la den fin."
  redmine_banner_title: "Ir a la configuración del baner."
  button_off: "Apagado"
  banner_off: "No mostrar el baner en la sesión. (El baner se volvera a encender si el admin lo modifica)"
  permission_manage_banner: "Administrar banner"
  project_module_banner: "Baner"
  page_overview_only: "Solo vista general"
  page_all: "En toda la pagina"
  page_overview_and_issues: "Vista general y tareas"
  page_new_issue_only: "Solo en nueva tarea"
  label_display_authenticated_user_only: "Mostrar solo el baner solo a los usuarios autenticados."
  lalel_check_if_banner_show_only_login_page: "Opción: Mostrar solo en la pagina de acceso."
  setting_banner_related_link: "Enlace relacionado"
  setting_banner_related_link_description: "Si se define, Enlace para obtener información adjunta."
  more_info: "[Más info]"
  label_more_info: "Enlace para más información."

**Comment by akiko-pusu** [comment]
Hello, @Picazamora!
Thank you so much for your contribution of translation file!
Sorry for my delayed reply. I'll include this file and your name in next release :)

**Comment by akiko-pusu** [comment]
Hi, @Picazamora 
I've just included above translation file into master branch.

Thanks again for your support!
Sincerely,
