### ISSUE TITLE
it.yml update

### ISSUE THREAD

**Issue by R-i-c-k-y** [akiko-pusu/redmine_banner#57]
add these lines:

  label_display_authenticated_user_only: "Mostra banner solo agli utenti autenticati."
  lalel_check_if_banner_show_only_login_page: "Opzione: mostra solo nella pagina di login."
  setting_banner_related_link: "Link collegato"
  setting_banner_related_link_description: "Se definito, viene allegato il link per ulteriori informazioni."
  more_info: "[Piu' Info]"
  label_more_info: "Link per ulteriori informazioni."

**Comment by akiko-pusu** [comment]
Hi, @R-i-c-k-y 
Thank you so much for your support and translation file!
I've just include on master branch.

Sincerely,
