### ISSUE TITLE
Redmine 3.x breaks backward support?

### ISSUE THREAD

**Issue by DarkSideGeek** [akiko-pusu/redmine_banner#65]
The README says "0.0.8 or higher" for Redmine 2.x, but 0.1.1 -- which is "higher" -- does not meet dependency requirements if applied on v2.3. I know I'm on an outdated version, but a bit more clarification would be nice. Thankfully releases are tagged so it is easy to revert to 0.0.8 and be up and running on 2.3.

**Comment by akiko-pusu** [comment]
Hi, @DarkSideGeek 
Thank you for your posting issue.
I’m going to above task, please wait for a while.
