### ISSUE TITLE
In responsible theme, scroll up remains project title bar.

### ISSUE THREAD

**Issue by torutk** [akiko-pusu/redmine_banner#68]
Server platform: Ruby 2.3.1, Redmine 3.3.0, and CentOS 6.8 64bit.
Client platform - A: Android 6.0.1, Chrome browser
Client platform - B: Windows 10, Firefox browser

In responsive theme, for example on an Android browser or Windows browser with small window size, when banner is active and the page is scrolled up, banner is gone but project title bar is not scrolled up and remains at original place.

- when banner is enabled and page shown

![responsible_scroll-1](https://cloud.githubusercontent.com/assets/2397032/16340634/2ee6c300-3a64-11e6-920e-764c55f9a998.png)

- scroll the page up 

![responsible_scroll-2](https://cloud.githubusercontent.com/assets/2397032/16340637/3034accc-3a64-11e6-8ddd-21c231b3dc93.png)

- and scroll the page up and up

![responsible_scroll-3](https://cloud.githubusercontent.com/assets/2397032/16340641/325d3622-3a64-11e6-8a45-a5bfbff7d377.png)

redmine theme is alternate.

**Comment by akiko-pusu** [comment]
Hi, @torutk. I appreciate your reporting this issue, and I’ve confirmed this defect.
This is also happened with other theme, such as http://redmine-akiko.ruby.iijgio.com (My demo site, running on Redmine 3.3).
Please wait for a while.

こんにちは、ご報告ありがとうございます！(日本語で大丈夫ですが、ご配慮ありがとうございます）
レスポンシブ対応は手を出さずにいたのですが、丁度良いタイミングですので、対応進めます。

一番シンプルなのは、読み込み時点では解像度が高い時と同じく、ヘッダツールバーの下にバナーが表示され、スクロールするとツールバーのみ固定でバナーは見えなくなる...という動作ですよね。

ただ、お知らせがあるというのは分かっていただきたいケースもあると思いますので、アイコン化するとか、フッタ側にバナーを出すようなことができればいいなとも思っています。

**Comment by akiko-pusu** [comment]
I’ve just update code to switch banner location when window resize event.
This workaround is applied on commit: 7204429, and merged dev branch. I’m going to release fixed version soon.
If you have time, please try dev branch and this meets your need or not.

**Comment by torutk** [comment]
I have tried dev branch. I confirmed on both Windows OS/Firefox small window size and Android smartphone/Chrome. It works.

The header banner is initially just under the project title bar, the banner is scralled up as page contents, and the project tite bar is remain on top. It seemed no problem.

**Comment by akiko-pusu** [comment]
Now merged dev into master, and released as v0.1.2.
Thanks again!
