### ISSUE TITLE
Reload plugin.html.erb

### ISSUE THREAD

**Issue by fairoj** [akiko-pusu/redmine_banner#75]
Hello, Akiko Takano.
You're overloaded plugin.html.erb file, that's too bad. Other plugins assume that indents will be as usual, and as a result of setting page layout breaks.

**Comment by akiko-pusu** [comment]
Hi, @fairoj 
Thank you so much for your reporting issue.
I’ll confirm this defect, loading views/settings/plugin.html.erb,  and try to fix.

**Comment by akiko-pusu** [comment]
Removed overwrites plugin.html.erb and merged into master branch.
Thank you for your reporting!
