### ISSUE TITLE
Give ability to specific users to manage the site-wide banner

### ISSUE THREAD

**Issue by pousterlus** [akiko-pusu/redmine_banner#86]
Hello,

Thanks very much for your work, your plugin is a real advantage.
I only have a suggestion : Do you think it would be possible to give the ability, for non-admin users, to show a site-wide banner instead per project like now ?

Because I would like to let only two users to print a global alert banner, but I don't want to give them the Administrator rights.

Cheers, and regards,

-- 
Léo, Paris - France.

**Comment by akiko-pusu** [comment]
@pousterlus 
Thanks for your feedback!
Do you still have requirement of this feature?

I’m planning that enabled global banner to have multiple records, as histories,  not to have only one banner message. 
To implement this, I also planning to add dedicated controller and model ti handle global banners.
So, maybe I could set the permissions for non-admin users to edit / update global banner.  

Please wait for a while.

**Comment by akiko-pusu** [comment]
Not based on role, but based on per user or group.

**Comment by akiko-pusu** [comment]
v0.2.1 released. This version has a prototype feature to be able to update site-wide banner via API.
The user who is assigned specified group can also update site-wide banner via API.
If this feature is effective, I’m going to add web ui on next release :)

**Comment by akiko-pusu** [comment]
Implemented on v0.3.0. Thanks for your feedback!
