### ISSUE TITLE
 Little error in spanish translation 

### ISSUE THREAD

**Issue by dani-sanchez-dorado** [akiko-pusu/redmine_banner#87]
There is an error in label: 
> error_banner_date_range: "La fecha de inicio debe ser anterior a la den fin."

correct label is:
> error_banner_date_range: "La fecha de inicio debe ser anterior a la de fin."
(Just an "n") 

Thanks!

**Comment by akiko-pusu** [comment]
@dani-sanchez-dorado Thanks for your reporting issue!
I7m going to update spanish translation file soon.

**Comment by akiko-pusu** [comment]
I've fixed above and merged into master branch. Thanks for your support!
