### ISSUE TITLE
How fixed the Edit Text formatting for banner

### ISSUE THREAD

**Issue by kay54068** [akiko-pusu/redmine_banner#93]
I really like this plugin...
I would like to add the following features:
 I will install Redmine per project formatting plugin to change Text formatting for per project,
 but i change to [redmine_ckeditor](https://github.com/a-ono/redmine_ckeditor/issues) , the formatting was wrong about this:
![image](https://user-images.githubusercontent.com/3054544/29023258-7e135128-7b9f-11e7-9a61-02fe8a3ccbaa.png)

but the homepage is fine:

![image](https://user-images.githubusercontent.com/3054544/29023284-9c0345ee-7b9f-11e7-98a2-29a62f388bab.png)

We system default  is Markdown formatting .

**Comment by akiko-pusu** [comment]
Hi, @kay54068
Thanks for your request and sorry for my tooooo late reply.....

By default, Redmine's editor setting is system wide, so I don't assume this situation.
Are you still in this trouble and do you still hope to implemeent this feature?

If so, could you tell me the information the plugin that you use:  "Redmine per project formatting plugin".
