### ISSUE TITLE
Redmine 4.0 not compatible

### ISSUE THREAD

**Issue by lublasco** [akiko-pusu/redmine_banner#96]
Hi,

I've tried to install the plugin in a Redmine 4.0 server and it shows the following error:

/opt/bitnami/apps/redmine/htdocs$ bundle exec rake redmine:plugins:migrate RAILS_ENV=production
rake aborted!
NameError: uninitialized constant Rake::TestTask
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_banner/lib/tasks/test.rake:7:in `block in <top (required)>'
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_banner/lib/tasks/test.rake:1:in `<top (required)>'
/opt/bitnami/apps/redmine/htdocs/lib/tasks/redmine.rake:190:in `load'
/opt/bitnami/apps/redmine/htdocs/lib/tasks/redmine.rake:190:in `block in <top (required)>'
/opt/bitnami/apps/redmine/htdocs/lib/tasks/redmine.rake:190:in `each'
/opt/bitnami/apps/redmine/htdocs/lib/tasks/redmine.rake:190:in `<top (required)>'
/opt/bitnami/apps/redmine/htdocs/Rakefile:7:in `<top (required)>'
/opt/bitnami/ruby/bin/bundle:23:in `load'
/opt/bitnami/ruby/bin/bundle:23:in `<main>'
(See full trace by running task with --trace)
bitnami@ip-172-31-42-244:/opt/bitnami/apps/redmine/htdocs$ bundle exec rake redmine:plugins:migrate RAILS_ENV=production
(See full trace by running task with --trace)

Do you intend to make it compatible with the new Redmine version? Thanks for your nice plugin!

**Comment by sense-design** [comment]
Would be great!

**Comment by akiko-pusu** [comment]
@lublasco @sense-design 
Thanks for your requests!
Now released v0.2.0, support Redmine4.x. Please note latest  / master branch does not support Redmine3.x.
Could you please try latest? Feedback highly appreciated because!

**Comment by lublasco** [comment]
Hi, @akiko-pusu 

Now it works perfectly. Thank you very much!

**Comment by akiko-pusu** [comment]
I'm glad to hear that!
